### ISSUE TITLE
 Subviews

### ISSUE THREAD

**Issue by erwindm** [kippesikgithub/ha_cards_interface#1]
Bedankt voor het delen, ik vindt deze zalig.

Zou je zo vriendelijk willen zijn om de code van "Kinderkamer Sophie Subview" te willen delen

Alleen willen bij mij de iconen" op de "Woonkamer Room Card" niet zo verdeeld staan, zoals bij jou en mijn hass herkent "type: custom:vertical-stack-in-card" niet,  ik moet deze veranderen in "type: vertical-stack"

**Comment by kippesikgithub** [comment]
- Ik zal komende dagen de sub views posten. 
- cards die niet gevonden worden via hacs installeren
- als je niet de vertical stack in gebruikt, staan je iconen idd op andere plekken

**Comment by erwindm** [comment]
Bedankt voor de tip, nu staan ze wel juist.
Ik zie er naar uit op je volgende posts

**Comment by kippesikgithub** [comment]
Documentation will be added piece by piece in the coming weeks

**Comment by kippesikgithub** [comment]
Ik heb weer een aantal documentatie stukken icm de subviews toegevoegd, FIY

**Comment by erwindm** [comment]
Super, 👍👍👍👍👍
Ik heb nog een vraagje ivm de slaapuren bij Sophie is het enkel een script om het icoon te veranderen of ook om de lichten te bedienen.

**Comment by kippesikgithub** [comment]
Bedoel je het nachtlampje / sleep trainer? 
Je kunt idd de tijden aanpassen door op de datetimes te klikken, door op oogjes dicht of oogjes open icoontje te klikken zet je de lamp handmatig in die modus. En met het grote icoon, zet je hem handmatig aan / uit, komt ie terug in de laatste status. Praktisch gezien bedienen we hem nooit, en passen we eigenlijk alleen de tijden aan. Node red kijkt naar die tijden, en schakeld dan de goede leds aan/uit. Helder genoeg?

**Comment by erwindm** [comment]
Perfect, bedankt voor je snelle reactie

**Comment by kippesikgithub** [comment]
Top, geen dank! Inmiddels ook weer wat updates gedaan, waaronder popup cards voor de personen ;)
