### ISSUE TITLE
Color question / initial setup.

### ISSUE THREAD

**Issue by hugo-leij** [kippesikgithub/ha_cards_interface#2]
Hi,

First of all, I would like to thank you for sharing your code. I have been looking for a good room card for a while and this is exactly what I am looking for / I can further organize it how I want.

Kudos!

This is what is had:
<img width="511" alt="image" src="https://github.com/kippesikgithub/ha_cards_interface/assets/10241984/583556b7-1433-4843-afec-d14ac2cb32b0">

But this just wasn't it for me, I just copied your code but the colors and borders are still not there. See a screenshot below.
<img width="535" alt="image" src="https://github.com/kippesikgithub/ha_cards_interface/assets/10241984/7be85d03-e1fe-4576-a812-375936baf3b1">

Can you help me in the right direction?

Thnx!

Gr Hugo

**Comment by kippesikgithub** [comment]
Thanks for the compliments! I kind of had the same problem not finding the card that matched our needs, when I started building this cards/interface. Now everything is so configurable that it can possible fit any need ;)

For hiding the borders and so on, I think there is a simple solution. Sorry, forgot to add that in the guide. Download the mushroom themes in hacs. And apply the 'mushroom shadow's theme to your dashboard (the one you put my code on). All the borders and so on will magically disappear ;) I also added it to the guide, thanks for notifying!

**Comment by hugo-leij** [comment]
Hi,

I entirely agree with that :D. Thanks for the explanation, I installed the theme last night and all the lines were immediately gone!

Only with the day view (light) they are still there. A quick Google search turns up nothing for me. It must have something to do with the next variable, but I can't get it right.
```
--ha-card-border-width: 0;
--ha-card-box-shadow: none;
```

Do you perhaps have an idea?

**Comment by kippesikgithub** [comment]
Great, that they are gone.
We only use the dark views everywhere, so not sure. 
I will have a look, and let you know.

**Comment by kippesikgithub** [comment]
Added description for adding mushroom shadow theme and apply to dashboard

**Comment by hugo-leij** [comment]
Hi,

When I inspect the element I can remove the shadow by unchecking the following.
`
:host
box-shadow: var(--ha-card-box-shadow, none);
`    
I can't find which value is being overwritten if I uncheck it.

<img width="1397" alt="image" src="https://github.com/kippesikgithub/ha_cards_interface/assets/10241984/b974b6a2-298a-4fab-8ec8-aec6235009b5">
