### ISSUE TITLE
Mini-graph-card from subview_trapkast_detailed_card

### ISSUE THREAD

**Issue by hugo-leij** [kippesikgithub/ha_cards_interface#3]
Hi,

I like your design from the mini-graph-card in your subview_trapkast_detailed_card. Would it be possible to post to GitHub?

<img width="561" alt="image" src="https://github.com/kippesikgithub/ha_cards_interface/assets/10241984/4bedecde-74d7-4933-99c0-1926bc3ec6dd">

Thnx

**Comment by kippesikgithub** [comment]
they were already in, but i added them seperately for you.
see: 
subview_trapkast_detailed_card.yaml 
subview_climate_trapkast_card.yaml
